FROM golang:1.26.4-alpine3.23@sha256:18b460dd17542c2ba43299a633cf6ebfc1115101509531471d7cfce1019af083

WORKDIR /app

RUN apk add git iputils bash bash-completion zsh fish
RUN echo "source /etc/bash/bash_completion.sh" >> ~/.bash_profile
RUN echo "source <(vmwiz-backend completion bash)" >> ~/.bashrc
RUN printf "%s\n" \
    "autoload -Uz compinit" \
    "compinit" \
    "source <(vmwiz-backend completion zsh)" \
    >> ~/.zshrc

RUN mkdir -p ~/.config/fish
RUN echo "vmwiz-backend completion fish 2>/dev/null | source" >> ~/.config/fish/config.fish


RUN go install github.com/air-verse/air@v1.64.5
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.31.1

COPY go.mod go.sum ./
RUN go mod download
