# backend/Dockerfile
FROM alpine:3.21

RUN apk add --no-cache ca-certificates
WORKDIR /app


COPY vmwiz-backend/migrations /app/migrations
COPY vmwiz-backend/proxmox/*.tmpl /app/proxmox/
COPY vmwiz-backend/survey/*.tmpl /app/survey/

ARG TARGETPLATFORM
COPY $TARGETPLATFORM/vmwiz-backend /app/vmwiz-backend

ENV ENV="production"
ENTRYPOINT ["/app/vmwiz-backend", "server"]
