# backend/Dockerfile
FROM alpine:3.23@sha256:fd791d74b68913cbb027c6546007b3f0d3bc45125f797758156952bc2d6daf40 AS build


WORKDIR /app

ARG TARGETPLATFORM
COPY $TARGETPLATFORM/vmwiz-backend /app/vmwiz-backend

FROM alpine:3.23@sha256:fd791d74b68913cbb027c6546007b3f0d3bc45125f797758156952bc2d6daf40 

COPY --from=build /app /app

RUN apk add --no-cache bash-completion bash zsh fish
RUN echo "source /etc/bash/bash_completion.sh" >> ~/.bash_profile
RUN echo "source <(vmwiz-backend completion bash)" >> ~/.bashrc
RUN printf "%s\n" \
    "autoload -Uz compinit" \
    "compinit" \
    "source <(vmwiz-backend completion zsh)" \
    >> ~/.zshrc

RUN mkdir -p ~/.config/fish
RUN echo "vmwiz-backend completion fish 2>/dev/null | source" >> ~/.config/fish/config.fish

ENV ENV="production"
RUN ln -s /app/vmwiz-backend /bin/vmwiz-backend
WORKDIR /app
ENTRYPOINT ["/app/vmwiz-backend", "server"]
