FROM golang:1.26.4-alpine3.23@sha256:f23e8b227fb4493eabe03bede4d5a32d04092da71962f1fb79b5f7d1e6c2a17f

WORKDIR /app

RUN apk add git iputils bash bash-completion zsh fish
RUN echo "source /etc/bash/bash_completion.sh" >> ~/.bash_profile
RUN echo "source <(vmwiz-backend completion bash)" >> ~/.bashrc
RUN printf "%s\n" \
    "autoload -Uz compinit" \
    "compinit" \
    "source <(vmwiz-backend completion zsh)" \
    >> ~/.zshrc

RUN mkdir -p ~/.config/fish
RUN echo "vmwiz-backend completion fish 2>/dev/null | source" >> ~/.config/fish/config.fish


RUN go install github.com/air-verse/air@v1.64.5
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.31.1

COPY go.mod go.sum ./
RUN go mod download
