name: "vmwiz-prod"

networks:
  vmwiz-internal:
    external: false

services:
  vmwiz-caddy:
    container_name: vmwiz-caddy
    image: caddy:2.11.2@sha256:1e40b251ca9639ead7b5cd2cedcc8765adfbabb99450fe23f130eefabf50f4bc
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - vmwiz-internal
    cap_add:
      - NET_ADMIN
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/Caddy/caddy_data:/data
      - ./data/Caddy/caddy_config:/config
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    env_file:
      - .env

  vmwiz-backend:
    container_name: vmwiz-backend
    image: docker.git.sos.ethz.ch/vsos/vmwiz.vsos.ethz.ch/backend:latest
    restart: unless-stopped
    expose:
      - 8081
    networks:
      - vmwiz-internal
    volumes:
      - ./ssh:/root/.ssh
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    env_file:
      - .env
      - .db.env
      - .backend.env
    depends_on:
      vmwiz-db:
        condition: service_healthy

  vmwiz-notifier:
    container_name: vmwiz-notifier
    image: caronc/apprise:v1.3.3@sha256:4bfeac268ba87b8e08e308c9aa0182fe99e9501ec464027afc333d1634e65977
    restart: unless-stopped
    networks:
      - vmwiz-internal
    volumes:
      - ${PWD}/notifier_config.yml:/config/default.yml
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    expose:
      - 8000
    environment:
      - APPRISE_STATEFUL_MODE=simple
      - APPRISE_DEFAULT_CONFIG_ID=default
      - APPRISE_WORKER_COUNT=1

  vmwiz-db:
    container_name: vmwiz-db
    image: postgres:18.3@sha256:a9abf4275f9e99bff8e6aed712b3b7dfec9cac1341bba01c1ffdfce9ff9fc34a
    restart: unless-stopped
    networks:
      - vmwiz-internal
    expose:
      - "5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    env_file:
      - .db.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1' || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  vmwiz-frontend:
    container_name: vmwiz-frontend
    image: docker.git.sos.ethz.ch/vsos/vmwiz.vsos.ethz.ch/frontend:latest
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - vmwiz-internal
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
