# We are using tags for associating backend events with specific services.
# You can see the available services on the apprise repo [See https://github.com/caronc/apprise#supported-notifications]

urls:
  # The Zulip tokens are just placeholders
