// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type RequestStatus string

const (
	RequestStatusAccepted RequestStatus = "accepted"
	RequestStatusRejected RequestStatus = "rejected"
	RequestStatusPending  RequestStatus = "pending"
	RequestStatusHold     RequestStatus = "hold"
)

func (e *RequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestStatus(s)
	case string:
		*e = RequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestStatus: %T", src)
	}
	return nil
}

type NullRequestStatus struct {
	RequestStatus RequestStatus
	Valid         bool // Valid is true if RequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestStatus), nil
}

type LogScope struct {
	ID        string
	ParentID  sql.NullString
	RootID    string
	Label     string
	StartedAt time.Time
	EndedAt   sql.NullTime
	Failed    bool
}

type Request struct {
	Requestid        int64
	Requestcreatedat time.Time
	Requeststatus    RequestStatus
	Email            string
	Personalemail    string
	Isorganization   bool
	Orgname          sql.NullString
	Hostname         string
	Image            string
	Cores            int32
	Ramgb            int32
	Diskgb           int32
	Sshpubkeys       []string
	Comments         sql.NullString
	Secondarydiskgb  int32
}

type Survey struct {
	ID   int64
	Date time.Time
}

type SurveyEmail struct {
	ID        int64
	Recipient string
	Surveyid  int64
	Vmid      int32
	Hostname  string
	Uuid      string
	EmailSent bool
	StillUsed sql.NullBool
}
