// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package storage

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const countNegativeSurveyEmails = `-- name: CountNegativeSurveyEmails :one
SELECT COUNT(*) FROM survey_email
WHERE surveyId = $1 AND (email_sent = TRUE AND still_used = FALSE)
`

func (q *Queries) CountNegativeSurveyEmails(ctx context.Context, surveyid int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNegativeSurveyEmails, surveyid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPositiveSurveyEmails = `-- name: CountPositiveSurveyEmails :one
SELECT COUNT(*) FROM survey_email
WHERE surveyId = $1 AND (email_sent = TRUE AND still_used = TRUE)
`

func (q *Queries) CountPositiveSurveyEmails(ctx context.Context, surveyid int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPositiveSurveyEmails, surveyid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnansweredSurveyEmails = `-- name: CountUnansweredSurveyEmails :one
SELECT COUNT(*) FROM survey_email
WHERE surveyId = $1 AND (email_sent = TRUE AND still_used IS NULL)
`

func (q *Queries) CountUnansweredSurveyEmails(ctx context.Context, surveyid int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnansweredSurveyEmails, surveyid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnsentSurveyEmails = `-- name: CountUnsentSurveyEmails :one
SELECT COUNT(*) FROM survey_email
WHERE surveyId = $1 AND (email_sent = FALSE)
`

func (q *Queries) CountUnsentSurveyEmails(ctx context.Context, surveyid int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnsentSurveyEmails, surveyid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLogScope = `-- name: CreateLogScope :exec
INSERT INTO log_scope (id, parent_id, root_id, label) VALUES ($1, $2, $3, $4)
`

type CreateLogScopeParams struct {
	ID       string
	ParentID sql.NullString
	RootID   string
	Label    string
}

func (q *Queries) CreateLogScope(ctx context.Context, arg CreateLogScopeParams) error {
	_, err := q.db.ExecContext(ctx, createLogScope,
		arg.ID,
		arg.ParentID,
		arg.RootID,
		arg.Label,
	)
	return err
}

const createSurvey = `-- name: CreateSurvey :one
INSERT INTO survey DEFAULT VALUES RETURNING id
`

func (q *Queries) CreateSurvey(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSurvey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSurveyEmail = `-- name: CreateSurveyEmail :one
INSERT INTO survey_email (
  recipient, surveyId, vmid, hostname, uuid, email_sent, still_used
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id
`

type CreateSurveyEmailParams struct {
	Recipient string
	Surveyid  int64
	Vmid      int32
	Hostname  string
	Uuid      string
	EmailSent bool
	StillUsed sql.NullBool
}

func (q *Queries) CreateSurveyEmail(ctx context.Context, arg CreateSurveyEmailParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSurveyEmail,
		arg.Recipient,
		arg.Surveyid,
		arg.Vmid,
		arg.Hostname,
		arg.Uuid,
		arg.EmailSent,
		arg.StillUsed,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createVMRequest = `-- name: CreateVMRequest :one
INSERT INTO request (
  email, personalEmail, isOrganization, orgName, hostname, image,
  cores, ramGB, diskGB, secondaryDiskGB, sshPubkeys, comments
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING requestID
`

type CreateVMRequestParams struct {
	Email           string
	Personalemail   string
	Isorganization  bool
	Orgname         sql.NullString
	Hostname        string
	Image           string
	Cores           int32
	Ramgb           int32
	Diskgb          int32
	Secondarydiskgb int32
	Sshpubkeys      []string
	Comments        sql.NullString
}

func (q *Queries) CreateVMRequest(ctx context.Context, arg CreateVMRequestParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createVMRequest,
		arg.Email,
		arg.Personalemail,
		arg.Isorganization,
		arg.Orgname,
		arg.Hostname,
		arg.Image,
		arg.Cores,
		arg.Ramgb,
		arg.Diskgb,
		arg.Secondarydiskgb,
		pq.Array(arg.Sshpubkeys),
		arg.Comments,
	)
	var requestid int64
	err := row.Scan(&requestid)
	return requestid, err
}

const finishLogScope = `-- name: FinishLogScope :exec
UPDATE log_scope SET ended_at = CURRENT_TIMESTAMP, failed = $2 WHERE id = $1
`

type FinishLogScopeParams struct {
	ID     string
	Failed bool
}

func (q *Queries) FinishLogScope(ctx context.Context, arg FinishLogScopeParams) error {
	_, err := q.db.ExecContext(ctx, finishLogScope, arg.ID, arg.Failed)
	return err
}

const getLatestSurveyID = `-- name: GetLatestSurveyID :one
SELECT id FROM survey ORDER BY date DESC LIMIT 1
`

func (q *Queries) GetLatestSurveyID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLatestSurveyID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getLogScopeRootID = `-- name: GetLogScopeRootID :one
SELECT root_id FROM log_scope WHERE id = $1
`

func (q *Queries) GetLogScopeRootID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLogScopeRootID, id)
	var root_id string
	err := row.Scan(&root_id)
	return root_id, err
}

const getLogScopeStatus = `-- name: GetLogScopeStatus :one
SELECT ended_at, failed FROM log_scope WHERE id = $1
`

type GetLogScopeStatusRow struct {
	EndedAt sql.NullTime
	Failed  bool
}

func (q *Queries) GetLogScopeStatus(ctx context.Context, id string) (GetLogScopeStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getLogScopeStatus, id)
	var i GetLogScopeStatusRow
	err := row.Scan(&i.EndedAt, &i.Failed)
	return i, err
}

const getSurveyByID = `-- name: GetSurveyByID :one
SELECT id, date FROM survey WHERE id = $1
`

func (q *Queries) GetSurveyByID(ctx context.Context, id int64) (Survey, error) {
	row := q.db.QueryRowContext(ctx, getSurveyByID, id)
	var i Survey
	err := row.Scan(&i.ID, &i.Date)
	return i, err
}

const getVMRequestByID = `-- name: GetVMRequestByID :one
SELECT requestid, requestcreatedat, requeststatus, email, personalemail, isorganization, orgname, hostname, image, cores, ramgb, diskgb, sshpubkeys, comments, secondarydiskgb FROM request WHERE requestID = $1
`

func (q *Queries) GetVMRequestByID(ctx context.Context, requestid int64) (Request, error) {
	row := q.db.QueryRowContext(ctx, getVMRequestByID, requestid)
	var i Request
	err := row.Scan(
		&i.Requestid,
		&i.Requestcreatedat,
		&i.Requeststatus,
		&i.Email,
		&i.Personalemail,
		&i.Isorganization,
		&i.Orgname,
		&i.Hostname,
		&i.Image,
		&i.Cores,
		&i.Ramgb,
		&i.Diskgb,
		pq.Array(&i.Sshpubkeys),
		&i.Comments,
		&i.Secondarydiskgb,
	)
	return i, err
}

const getVMRequestsByHostname = `-- name: GetVMRequestsByHostname :many
SELECT requestid, requestcreatedat, requeststatus, email, personalemail, isorganization, orgname, hostname, image, cores, ramgb, diskgb, sshpubkeys, comments, secondarydiskgb FROM request WHERE hostname = $1
`

func (q *Queries) GetVMRequestsByHostname(ctx context.Context, hostname string) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, getVMRequestsByHostname, hostname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.Requestid,
			&i.Requestcreatedat,
			&i.Requeststatus,
			&i.Email,
			&i.Personalemail,
			&i.Isorganization,
			&i.Orgname,
			&i.Hostname,
			&i.Image,
			&i.Cores,
			&i.Ramgb,
			&i.Diskgb,
			pq.Array(&i.Sshpubkeys),
			&i.Comments,
			&i.Secondarydiskgb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredRootLogScopeIDs = `-- name: ListExpiredRootLogScopeIDs :many
SELECT id FROM log_scope
WHERE id = root_id
  AND id <> $1
  AND ended_at IS NOT NULL
  AND ended_at < $2
`

type ListExpiredRootLogScopeIDsParams struct {
	RootScopeID string
	Cutoff      sql.NullTime
}

func (q *Queries) ListExpiredRootLogScopeIDs(ctx context.Context, arg ListExpiredRootLogScopeIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredRootLogScopeIDs, arg.RootScopeID, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogScopeSubtreeIDs = `-- name: ListLogScopeSubtreeIDs :many
WITH RECURSIVE subtree AS (
  SELECT log_scope.id FROM log_scope WHERE log_scope.id = $1
  UNION ALL
  SELECT c.id FROM log_scope c JOIN subtree st ON c.parent_id = st.id
)
SELECT subtree.id FROM subtree
`

func (q *Queries) ListLogScopeSubtreeIDs(ctx context.Context, id string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listLogScopeSubtreeIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNegativeSurveyHostnames = `-- name: ListNegativeSurveyHostnames :many
SELECT hostname FROM survey_email
WHERE surveyId = $1 AND (email_sent = TRUE AND still_used = FALSE)
`

func (q *Queries) ListNegativeSurveyHostnames(ctx context.Context, surveyid int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listNegativeSurveyHostnames, surveyid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var hostname string
		if err := rows.Scan(&hostname); err != nil {
			return nil, err
		}
		items = append(items, hostname)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositiveSurveyHostnames = `-- name: ListPositiveSurveyHostnames :many
SELECT hostname FROM survey_email
WHERE surveyId = $1 AND (email_sent = TRUE AND still_used = TRUE)
`

func (q *Queries) ListPositiveSurveyHostnames(ctx context.Context, surveyid int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPositiveSurveyHostnames, surveyid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var hostname string
		if err := rows.Scan(&hostname); err != nil {
			return nil, err
		}
		items = append(items, hostname)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootLogScopes = `-- name: ListRootLogScopes :many
SELECT id, parent_id, root_id, label, started_at, ended_at, failed FROM log_scope
WHERE id = root_id
  AND id <> $1
  AND ($2::text = '' OR id < $2::text)
ORDER BY id DESC
LIMIT $3
`

type ListRootLogScopesParams struct {
	RootScopeID string
	BeforeID    string
	MaxResults  int32
}

// Top-level scopes (id = root_id) newest-first. IDs are time-ordered, so before_id pages to scopes created before it; pass ” to start from newest.
func (q *Queries) ListRootLogScopes(ctx context.Context, arg ListRootLogScopesParams) ([]LogScope, error) {
	rows, err := q.db.QueryContext(ctx, listRootLogScopes, arg.RootScopeID, arg.BeforeID, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogScope{}
	for rows.Next() {
		var i LogScope
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.RootID,
			&i.Label,
			&i.StartedAt,
			&i.EndedAt,
			&i.Failed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentUnansweredSurveyEmails = `-- name: ListSentUnansweredSurveyEmails :many
SELECT id, recipient, surveyid, vmid, hostname, uuid, email_sent, still_used FROM survey_email
WHERE surveyId = $1 AND (still_used IS NULL AND email_sent = TRUE)
`

func (q *Queries) ListSentUnansweredSurveyEmails(ctx context.Context, surveyid int64) ([]SurveyEmail, error) {
	rows, err := q.db.QueryContext(ctx, listSentUnansweredSurveyEmails, surveyid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SurveyEmail{}
	for rows.Next() {
		var i SurveyEmail
		if err := rows.Scan(
			&i.ID,
			&i.Recipient,
			&i.Surveyid,
			&i.Vmid,
			&i.Hostname,
			&i.Uuid,
			&i.EmailSent,
			&i.StillUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSurveyIDs = `-- name: ListSurveyIDs :many
SELECT id FROM survey ORDER BY id
`

func (q *Queries) ListSurveyIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listSurveyIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSurveys = `-- name: ListSurveys :many
SELECT id, date FROM survey ORDER BY id
`

func (q *Queries) ListSurveys(ctx context.Context) ([]Survey, error) {
	rows, err := q.db.QueryContext(ctx, listSurveys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Survey{}
	for rows.Next() {
		var i Survey
		if err := rows.Scan(&i.ID, &i.Date); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnansweredOrUnsentSurveyEmails = `-- name: ListUnansweredOrUnsentSurveyEmails :many
SELECT id, recipient, surveyid, vmid, hostname, uuid, email_sent, still_used FROM survey_email
WHERE surveyId = $1 AND (still_used IS NULL OR email_sent = FALSE)
`

func (q *Queries) ListUnansweredOrUnsentSurveyEmails(ctx context.Context, surveyid int64) ([]SurveyEmail, error) {
	rows, err := q.db.QueryContext(ctx, listUnansweredOrUnsentSurveyEmails, surveyid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SurveyEmail{}
	for rows.Next() {
		var i SurveyEmail
		if err := rows.Scan(
			&i.ID,
			&i.Recipient,
			&i.Surveyid,
			&i.Vmid,
			&i.Hostname,
			&i.Uuid,
			&i.EmailSent,
			&i.StillUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnansweredSurveyHostnames = `-- name: ListUnansweredSurveyHostnames :many
SELECT hostname FROM survey_email
WHERE surveyId = $1 AND (email_sent = TRUE AND still_used IS NULL)
`

func (q *Queries) ListUnansweredSurveyHostnames(ctx context.Context, surveyid int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUnansweredSurveyHostnames, surveyid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var hostname string
		if err := rows.Scan(&hostname); err != nil {
			return nil, err
		}
		items = append(items, hostname)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsentSurveyEmails = `-- name: ListUnsentSurveyEmails :many
SELECT id, recipient, surveyid, vmid, hostname, uuid, email_sent, still_used FROM survey_email
WHERE surveyId = $1 AND (email_sent = FALSE)
`

func (q *Queries) ListUnsentSurveyEmails(ctx context.Context, surveyid int64) ([]SurveyEmail, error) {
	rows, err := q.db.QueryContext(ctx, listUnsentSurveyEmails, surveyid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SurveyEmail{}
	for rows.Next() {
		var i SurveyEmail
		if err := rows.Scan(
			&i.ID,
			&i.Recipient,
			&i.Surveyid,
			&i.Vmid,
			&i.Hostname,
			&i.Uuid,
			&i.EmailSent,
			&i.StillUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsentSurveyHostnames = `-- name: ListUnsentSurveyHostnames :many
SELECT hostname FROM survey_email
WHERE surveyId = $1 AND email_sent = FALSE
`

func (q *Queries) ListUnsentSurveyHostnames(ctx context.Context, surveyid int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUnsentSurveyHostnames, surveyid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var hostname string
		if err := rows.Scan(&hostname); err != nil {
			return nil, err
		}
		items = append(items, hostname)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMRequests = `-- name: ListVMRequests :many
SELECT requestid, requestcreatedat, requeststatus, email, personalemail, isorganization, orgname, hostname, image, cores, ramgb, diskgb, sshpubkeys, comments, secondarydiskgb FROM request ORDER BY requestID
`

func (q *Queries) ListVMRequests(ctx context.Context) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listVMRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.Requestid,
			&i.Requestcreatedat,
			&i.Requeststatus,
			&i.Email,
			&i.Personalemail,
			&i.Isorganization,
			&i.Orgname,
			&i.Hostname,
			&i.Image,
			&i.Cores,
			&i.Ramgb,
			&i.Diskgb,
			pq.Array(&i.Sshpubkeys),
			&i.Comments,
			&i.Secondarydiskgb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSurveyEmailSent = `-- name: MarkSurveyEmailSent :exec
UPDATE survey_email SET email_sent = TRUE WHERE uuid = $1
`

func (q *Queries) MarkSurveyEmailSent(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, markSurveyEmailSent, uuid)
	return err
}

const surveyEmailExistsByUUID = `-- name: SurveyEmailExistsByUUID :one
SELECT EXISTS(SELECT 1 FROM survey_email WHERE uuid = $1)
`

func (q *Queries) SurveyEmailExistsByUUID(ctx context.Context, uuid string) (bool, error) {
	row := q.db.QueryRowContext(ctx, surveyEmailExistsByUUID, uuid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSurveyEmailResponse = `-- name: UpdateSurveyEmailResponse :exec
UPDATE survey_email SET still_used = $2 WHERE uuid = $1
`

type UpdateSurveyEmailResponseParams struct {
	Uuid      string
	StillUsed sql.NullBool
}

func (q *Queries) UpdateSurveyEmailResponse(ctx context.Context, arg UpdateSurveyEmailResponseParams) error {
	_, err := q.db.ExecContext(ctx, updateSurveyEmailResponse, arg.Uuid, arg.StillUsed)
	return err
}

const updateVMRequest = `-- name: UpdateVMRequest :exec
UPDATE request SET
  requestCreatedAt = $2,
  requestStatus = $3,
  email = $4,
  personalEmail = $5,
  isOrganization = $6,
  orgName = $7,
  hostname = $8,
  image = $9,
  cores = $10,
  ramGB = $11,
  diskGB = $12,
  secondaryDiskGB = $13,
  sshPubkeys = $14,
  comments = $15
WHERE requestID = $1
`

type UpdateVMRequestParams struct {
	Requestid        int64
	Requestcreatedat time.Time
	Requeststatus    RequestStatus
	Email            string
	Personalemail    string
	Isorganization   bool
	Orgname          sql.NullString
	Hostname         string
	Image            string
	Cores            int32
	Ramgb            int32
	Diskgb           int32
	Secondarydiskgb  int32
	Sshpubkeys       []string
	Comments         sql.NullString
}

func (q *Queries) UpdateVMRequest(ctx context.Context, arg UpdateVMRequestParams) error {
	_, err := q.db.ExecContext(ctx, updateVMRequest,
		arg.Requestid,
		arg.Requestcreatedat,
		arg.Requeststatus,
		arg.Email,
		arg.Personalemail,
		arg.Isorganization,
		arg.Orgname,
		arg.Hostname,
		arg.Image,
		arg.Cores,
		arg.Ramgb,
		arg.Diskgb,
		arg.Secondarydiskgb,
		pq.Array(arg.Sshpubkeys),
		arg.Comments,
	)
	return err
}

const updateVMRequestStatus = `-- name: UpdateVMRequestStatus :exec
UPDATE request SET requestStatus = $2 WHERE requestID = $1
`

type UpdateVMRequestStatusParams struct {
	Requestid     int64
	Requeststatus RequestStatus
}

func (q *Queries) UpdateVMRequestStatus(ctx context.Context, arg UpdateVMRequestStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateVMRequestStatus, arg.Requestid, arg.Requeststatus)
	return err
}
