FROM node:24.11.1-alpine3.21@sha256:b8f7c9056af700568c1ce76173f1c93743fb64ca1343e18cdf3a6ded8985ad3d as build

# Frontend files will be provided by Goreleaser
COPY vmwiz-frontend/ /app

WORKDIR /app

ENV VMWIZ_SCHEME=https
ENV VMWIZ_HOSTNAME=vmwiz.vsos.ethz.ch
ENV VMWIZ_PORT=443
ENV NODE_ENV=production 

RUN yarn install
RUN yarn run build

FROM node:24.11.1-alpine3.21@sha256:b8f7c9056af700568c1ce76173f1c93743fb64ca1343e18cdf3a6ded8985ad3d
COPY --from=build /app/dist /usr/share/nginx/html
WORKDIR /usr/share/nginx/html
