FROM node:20.19.6-alpine3.21@sha256:eb0b81f6eb35ec5ecd1cab181801f93a6314127580b416e6e290363b724e1686
WORKDIR /app

# Frontend files will be provided by Goreleaser
COPY vmwiz-frontend/ ./

ENV VMWIZ_SCHEME=https
ENV VMWIZ_HOSTNAME=vmwiz.vsos.ethz.ch
ENV VMWIZ_PORT=443
ENV NODE_ENV=production 

RUN yarn install
RUN yarn run build

FROM node:20.19.6-alpine3.21@sha256:eb0b81f6eb35ec5ecd1cab181801f93a6314127580b416e6e290363b724e1686
COPY --from=build /app/dist /usr/share/nginx/html
WORKDIR /usr/share/nginx/html
