FROM node:24.11.1-alpine3.21@sha256:b8f7c9056af700568c1ce76173f1c93743fb64ca1343e18cdf3a6ded8985ad3d AS build

# Frontend files will be provided by Goreleaser
COPY vmwiz-frontend/ /app

WORKDIR /app

ENV VMWIZ_SCHEME=https
ENV VMWIZ_HOSTNAME=vmwiz.vsos.ethz.ch
ENV VMWIZ_PORT=443
ENV NODE_ENV=production 

RUN yarn install
RUN yarn run build

FROM nginx:1.29.6-alpine3.23@sha256:f46cb72c7df02710e693e863a983ac42f6a9579058a59a35f1ae36c9958e4ce0
COPY --from=build /app/dist /usr/share/nginx/html
WORKDIR /usr/share/nginx/html
